/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ies.torredelrey.vista;

import ies.torredelrey.controlador.AddressJpaController;
import ies.torredelrey.controlador.DocumentJpaController;
import ies.torredelrey.controlador.OrdersJpaController;
import ies.torredelrey.controlador.PositionsJpaController;
import ies.torredelrey.controlador.ProductJpaController;
import ies.torredelrey.generador.Generador;
import javax.crypto.AEADBadTagException;
import javax.persistence.Entity;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author usuario
 */
public class Menu extends javax.swing.JFrame {
    //Controladores
    static AddressJpaController addressController = null;
    static DocumentJpaController documentController = null;
    static OrdersJpaController ordersController = null;  
    static PositionsJpaController positionsController = null;  
    static ProductJpaController productController = null;  
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //Ajustes visuales
        setTitle("Menú");
        setLocationRelativeTo(this);
        setResizable(false);
        
        //Conexion Base de datos
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        addressController = new AddressJpaController(emf);
        documentController = new DocumentJpaController(emf);
        ordersController = new OrdersJpaController(emf);
        positionsController = new PositionsJpaController(emf);
        productController = new ProductJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuInformes = new javax.swing.JMenu();
        jMenuItemListadoFacturas = new javax.swing.JMenuItem();
        jMenuItemVentasTotales = new javax.swing.JMenuItem();
        jMenuItemFacturasCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuInformes.setText("Informes");

        jMenuItemListadoFacturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemListadoFacturas.setText("Listado Facturas");
        jMenuItemListadoFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoFacturasActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemListadoFacturas);

        jMenuItemVentasTotales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVentasTotales.setText("Ventas Totales");
        jMenuItemVentasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasTotalesActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemVentasTotales);

        jMenuItemFacturasCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFacturasCliente.setText("Facturas por Cliente");
        jMenuItemFacturasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFacturasClienteActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemFacturasCliente);

        jMenuBar.add(jMenuInformes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListadoFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListadoFacturasActionPerformed

    private void jMenuItemVentasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVentasTotalesActionPerformed

    private void jMenuItemFacturasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacturasClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFacturasClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItemFacturasCliente;
    private javax.swing.JMenuItem jMenuItemListadoFacturas;
    private javax.swing.JMenuItem jMenuItemVentasTotales;
    // End of variables declaration//GEN-END:variables
}
